openapi: 3.0.3
info:
  title: Vertragsverwaltung API
  description: API zur Verwaltung von Verträgen.
  version: 1.0.0
servers:
  - url: /api/vertragsverwaltung
    description: Relative base url
  - url: http://localhost:8080/api/vertragsverwaltung
    description: Local Dev
paths:
  /vertrage:
    get:
      summary: Alle Verträge abrufen
      responses:
        '200':
          description: Erfolgreiche Antwort mit allen Verträgen
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VertragDTO'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        '401':
          description: Unauthenticated
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        '403':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        '404':
          description: Keine Verträge gefunden
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        default:
          description: Unexpected Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
    put:
      summary: Neuen Vertrag erstellen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VertragDTO'
      responses:
        '200':
          description: Created
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        '401':
          description: Unauthenticated
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        '403':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        default:
          description: Unexpected Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
  /vertrage/{id}:
    get:
      summary: Vertrag nach ID abrufen
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Vertrag gefunden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VertragDTO'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        '401':
          description: Unauthenticated
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        '403':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        '404':
          description: Vertrag nicht gefunden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        default:
          description: Unexpected Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
    post:
      summary: Vertrag aktualisieren
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        '200':
          description: Vertrag erfolgreich aktualisiert
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VertragDTO'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        '401':
          description: Unauthenticated
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        '403':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        '404':
          description: Vertrag nicht gefunden
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        default:
          description: Unexpected Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
    delete:
      summary: Vertrag löschen
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Vertrag erfolgreich gelöscht
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/VertragDTO"
        '204':
          description: Vertrag erfolgreich gelöscht
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/VertragDTO"
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        '401':
          description: Unauthenticated
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        '403':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        '404':
          description: Vertrag nicht gefunden
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        default:
          description: Unexpected Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
components:
  schemas:
    Preis:
      type: object
      required:
        - factor
        - factorage
        - factorspeed
      properties:
        speed:
          type: number
          format: double
          minimum: 0.0000001
          maximum: 9.9999999
          example: 0.7
          description: "Geschwindigkeitsfaktor, muss größer als 0 und kleiner als 10 sein."

        age:
          type: number
          format: double
          minimum: 0.0000001
          maximum: 9.9999999
          example: 0.3
          description: "Alter (in Jahren), muss größer als 0 und kleiner als 10 sein."

        faktor:
          type: number
          format: double
          minimum: 0.0000001
          maximum: 9.9999999
          example: 1.7
          description: "Multiplikationsfaktor, muss größer als 0 und kleiner als 10 sein."
    VertragDTO:
      type: object
      required:
        - monatlich
        - versicherungsbeginn
        - antragsDatum
        - partner
        - fahrzeug
      properties:

        monatlich:
          type: boolean
          example: true
          description: "Gibt an, ob die Zahlung monatlich erfolgt (true) oder jährlich (false)."

        versicherungsbeginn:
          type: string
          format: date
          example: "2025-01-01"
          description: "Startdatum der Versicherung im Format 'yyyy-MM-dd'."

        versicherungsablauf:
          type: string
          format: date
          example: "2026-01-01"
          description: "Ablaufdatum der Versicherung im Format 'yyyy-MM-dd'."

        antragsDatum:
          type: string
          format: date
          example: "2024-12-15"
          description: "Datum des Versicherungsantrags im Format 'yyyy-MM-dd'."

        fahrzeug:
          $ref: "#/components/schemas/FahrzeugDTO"

        partner:
          $ref: "#/components/schemas/PartnerDTO"
    PartnerDTO:
      type: object
      required:
        - vorname
        - nachname
        - geschlecht
        - geburtsdatum
        - land
        - strasse
        - hausnummer
        - plz
        - stadt
        - bundesland
      properties:
        vorname:
          type: string
          pattern: "^[a-zA-Z0-9\\s-äöüÄÖÜçéèêáàâíìîóòôúùûñÑ'-]+$"
          example: "Max"
          description: "Vorname der Person, erlaubt Buchstaben, Zahlen, Leerzeichen, Bindestriche und Apostrophe."

        nachname:
          type: string
          pattern: "^[a-zA-Z0-9\\s-äöüÄÖÜçéèêáàâíìîóòôúùûñÑ'-]+$"
          example: "Müller"
          description: "Nachname der Person mit denselben Zeichenbeschränkungen wie der Vorname."

        geschlecht:
          type: string
          pattern: "^[MmWwDd]$"
          minLength: 1
          maxLength: 1
          example: "M"
          description: "Geschlecht als einzelnes Zeichen ('M', 'W', 'D'), groß oder klein."

        geburtsdatum:
          type: string
          format: date
          example: "1990-05-15"
          description: "Geburtsdatum im Format 'yyyy-MM-dd'."

        land:
          type: string
          pattern: "^Deutschland$"
          example: "Deutschland"
          description: "Nur 'Deutschland' ist als Wohnsitzland erlaubt."

        strasse:
          type: string
          example: "Hauptstraße"
          description: "Straßenname der Wohnadresse."

        hausnummer:
          type: string
          pattern: "^\\d+[a-zA-Z]?(-[a-zA-Z])?$"
          example: "1"
          description: "Hausnummer im Format: Zahl gefolgt von optionalem Buchstaben oder Bindestrich + Buchstabe (z. B. '12', '12A', '12-B')."

        plz:
          type: string
          pattern: "^\\d{5}$"
          example: "10317"
          description: "Postleitzahl mit 5 Ziffern."

        stadt:
          type: string
          example: "Berlin"
          description: "Stadt der Wohnadresse."

        bundesland:
          type: string
          example: "Berlin"
          description: "Bundesland der Wohnadresse."
    FahrzeugDTO:
      type: object
      required:
        - amtlichesKennzeichen
        - hersteller
        - typ
        - hoechstgeschwindigkeit
        - wagnisskennziffer
      properties:
        amtlichesKennzeichen:
          type: string
          example: "M-AB1234E"
          description: "Amtliches Kfz-Kennzeichen im deutschen Format (z. B. M-AB1234 oder B-CD12E)."

        hersteller:
          type: string
          example: "Volkswagen"
          description: "Hersteller des Fahrzeugs (z. B. BMW, Audi, Volkswagen)."

        typ:
          type: string
          pattern: "^[a-zA-Z0-9\\s-äöüÄÖÜçéèêáàâíìîóòôúùûñÑ]+$"
          example: "Golf GTI"
          description: "Fahrzeugtyp oder Modellbezeichnung."

        hoechstgeschwindigkeit:
          type: integer
          format: int32
          minimum: 61
          maximum: 250
          example: 220
          description: "Maximale Geschwindigkeit des Fahrzeugs in km/h (muss zwischen 61 und 250 liegen)."

        wagnisskennziffer:
          type: integer
          minimum: 112
          maximum: 112
          example: 112
          description: "Wagniskennziffer für die Versicherungseinstufung."
    Problem:
      type: object
      description: AXA extension of the problem structure
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type. When dereferenced
            it SHOULD provide human-readable documentation for the problem type
            (e.g. using HTML).
          default: 'about:blank'
          example: 'https://www.axa.com/api/problem/constraint-violation'
          minLength: 0
          maxLength: 100
        title:
          type: string
          description: |
            A short summary of the problem type. Written in english and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized); example: Service Unavailable
          example: Constraint Violation
          minLength: 0
          maxLength: 150
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
          example: 500
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the
            problem.
          example: Connection to backend timed out
          minLength: 0
          maxLength: 300
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
          example: 'https://www.axa.com/api/customer/4711'
          minLength: 0
          maxLength: 300
        errorcode:
          type: string
          description: Optional additional error code to signal a more detailed error.
          example: '401.001'
          minLength: 0
          maxLength: 19
        timestamp:
          type: string
          description: Optional timestamp by when the problem occurred.
          format: date-time
          example: '2018-11-04T08:58:05:246Z'
        violations:
          type: array
          description: List of validation errors.
          example: '[{ field: "name", message: "Invalid name"}]'
          items:
            type: object
            description: The violation item.
            properties:
              field:
                type: string
                description: Json pointer to the field where the problem occour
                example: customer.name
                minLength: 0
                maxLength: 100
              message:
                type: string
                description: The problem message description
                example: The name is missing
                minLength: 0
                maxLength: 200
          minItems: 1